# Site settings
title: Liesbeth Van Lancker
email: liesbethvanlancker@gmail.com
description: Liesbeth Van Lancker is a nontoxic printmaker from Ghent, Belgium. Liesbeth draws, etches and occasionally uses soft ground, dry point and monotype. She teaches printmaking at the Academie voor Beeldende Kunst in Gent.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://liesbethvanlancker.be" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

gems:
- jekyll-email-protect

sass:
    style: compressed
